"""
Pydantic Schemas
================
Request and response schemas for the Health Dashboard API
"""

from app.schemas.users import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserPasswordChange,
    UserResponse,
    UserWithSettings,
    UserSettingsBase,
    UserSettingsUpdate,
    UserSettingsResponse,
    DataSourceBase,
    DataSourceCreate,
    DataSourceUpdate,
    DataSourceResponse,
)

from app.schemas.auth import (
    Token,
    TokenPayload,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RegisterRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
)

from app.schemas.metrics import (
    MetricDefinitionBase,
    MetricDefinitionResponse,
    MetricDefinitionList,
    MeasurementBase,
    MeasurementCreate,
    MeasurementBulkCreate,
    MeasurementResponse,
    MeasurementQuery,
    MeasurementAggregation,
    MeasurementTimeSeries,
    MeasurementStats,
    LatestMeasurement,
    LatestMeasurementsList,
    CorrelationRequest,
    CorrelationResult,
    CorrelationMatrix,
)

from app.schemas.activities import (
    WorkoutBase,
    WorkoutCreate,
    WorkoutUpdate,
    WorkoutResponse,
    WorkoutSummary,
    WorkoutStreak,
    SleepSessionBase,
    SleepSessionCreate,
    SleepSessionResponse,
    SleepSummary,
    SleepStagesBreakdown,
    DailySummaryBase,
    DailySummaryResponse,
    DailySummaryTrend,
    DashboardOverview,
    DashboardWidget,
    DashboardConfig,
)

from app.schemas.analytics import (
    ImportCreate,
    ImportProgress,
    ImportResponse,
    ImportSummary,
    InsightBase,
    InsightResponse,
    InsightUpdate,
    InsightsList,
    InsightFilters,
    AlertBase,
    AlertCreate,
    AlertUpdate,
    AlertResponse,
    AlertMute,
    AlertNotificationResponse,
    AlertTestResult,
    TrendAnalysis,
    AnomalyDetection,
    HealthReport,
    ExportRequest,
    ExportResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPasswordChange",
    "UserResponse",
    "UserWithSettings",
    "UserSettingsBase",
    "UserSettingsUpdate",
    "UserSettingsResponse",
    "DataSourceBase",
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    
    # Auth schemas
    "Token",
    "TokenPayload",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RegisterRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    
    # Metric schemas
    "MetricDefinitionBase",
    "MetricDefinitionResponse",
    "MetricDefinitionList",
    "MeasurementBase",
    "MeasurementCreate",
    "MeasurementBulkCreate",
    "MeasurementResponse",
    "MeasurementQuery",
    "MeasurementAggregation",
    "MeasurementTimeSeries",
    "MeasurementStats",
    "LatestMeasurement",
    "LatestMeasurementsList",
    "CorrelationRequest",
    "CorrelationResult",
    "CorrelationMatrix",
    
    # Activity schemas
    "WorkoutBase",
    "WorkoutCreate",
    "WorkoutUpdate",
    "WorkoutResponse",
    "WorkoutSummary",
    "WorkoutStreak",
    "SleepSessionBase",
    "SleepSessionCreate",
    "SleepSessionResponse",
    "SleepSummary",
    "SleepStagesBreakdown",
    "DailySummaryBase",
    "DailySummaryResponse",
    "DailySummaryTrend",
    "DashboardOverview",
    "DashboardWidget",
    "DashboardConfig",
    
    # Analytics schemas
    "ImportCreate",
    "ImportProgress",
    "ImportResponse",
    "ImportSummary",
    "InsightBase",
    "InsightResponse",
    "InsightUpdate",
    "InsightsList",
    "InsightFilters",
    "AlertBase",
    "AlertCreate",
    "AlertUpdate",
    "AlertResponse",
    "AlertMute",
    "AlertNotificationResponse",
    "AlertTestResult",
    "TrendAnalysis",
    "AnomalyDetection",
    "HealthReport",
    "ExportRequest",
    "ExportResponse",
]
